fix kafka config
java.lang.IllegalArgumentException: requirement failed: Each listener must have a different port, listeners: INTERNAL://kafka:9092,OUTSIDE://kafka:9092
	at scala.Predef$.require(Predef.scala:338)
	at kafka.utils.CoreUtils$.validate$1(CoreUtils.scala:264)
	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:275)
	at kafka.server.KafkaConfig.$anonfun$listeners$1(KafkaConfig.scala:1808)
	at scala.Option.map(Option.scala:242)
	at kafka.server.KafkaConfig.listeners(KafkaConfig.scala:1807)
	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1930)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1896)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1389)
	at kafka.Kafka$.buildServer(Kafka.scala:67)
	at kafka.Kafka$.main(Kafka.scala:87)
	at kafka.Kafka.main(Kafka.scala)